#!/bin/bash

Help()
{
   # Display Help
   echo "Bash script that runs the training routine in the context of the MICCAI 2023 project"
   echo
   echo "Syntax: run_training [w|d|g]"
   echo "required inputs:"
   echo "w     Working folder (where the scripts are)"
   echo "g     GPU number on which to run testing"
   echo
}

while getopts w:hm:g:d: option; do
case "${option}" in
   h) # display Help
       Help
       exit;;
   w) working_folder=${OPTARG};;
   d) dataset_folder=${OPTARG};;
   g) gpu=${OPTARG};;

   \?) # incorrect option
         echo "Error: Invalid input"
         exit 1
esac
done

# make sure to have the right conda environment open when running the script
# activate conda environment
eval "$(conda shell.bash hook)"
conda activate MICCAI2023_TF

# work on GPU 0
export CUDA_VISIBLE_DEVICES=$gpu

# go to the working folder
cd $working_folder

# #################
# DEFINE PARAMETERS
# #################
WORKING_FOLDER=$working_folder
IMG_DATASET_FOLDER=/flush/iulta54/Research/Data/CBTN/EXTRACTED_SLICES_TFR_MERGED_FROM_TB_20230320
DATASET_TYPE="CBTN"
TFR_DATA=True
MR_MODALITIES="T2"
NBR_CLASSES=3

MODEL_TYPE="SDM4"
MODEL_NAME="Classification"
USE_PRETRAINED_MODEL=False
DATA_NORMALIZATION=True
DATA_AUGMENTATION=True
DATA_SCALE=True

USE_AGE=True
AGE_NORMALIZATION=True

USE_GRADCAM=False

NBR_FOLDS=5
BATCH_SIZE=32
MAX_EPOCHS=75

OPTIMIZER="ADAM"
LOSS="MCC_and_CCE_Loss" 
LEARNING_RATE=0.0001

DEBUG_DATASET_FRACTION=1


GPU_NBR=$gpu

# ##############
echo "#### RUNNING TRAINING WITH NO AGE INFORMATION"
# ##############
USE_AGE=False
AGE_ENCODER_VERSION=None

for RANDOM_SEED_NUMBER in 1111 1112 1113 1114 1115
do
   python3 run_model_training_TF.py --WORKING_FOLDER $WORKING_FOLDER --IMG_DATASET_FOLDER $IMG_DATASET_FOLDER --DATASET_TYPE $DATASET_TYPE --NBR_CLASSES $NBR_CLASSES --GPU_NBR $GPU_NBR --NBR_FOLDS $NBR_FOLDS --LEARNING_RATE $LEARNING_RATE --BATCH_SIZE $BATCH_SIZE --MAX_EPOCHS $MAX_EPOCHS --USE_AGE $USE_AGE --AGE_NORMALIZATION $AGE_NORMALIZATION --AGE_ENCODER_VERSION $AGE_ENCODER_VERSION --USE_GRADCAM $USE_GRADCAM --LOSS $LOSS --RANDOM_SEED_NUMBER $RANDOM_SEED_NUMBER --MR_MODALITIES $MR_MODALITIES --DEBUG_DATASET_FRACTION $DEBUG_DATASET_FRACTION --TFR_DATA $TFR_DATA --MODEL_TYPE $MODEL_TYPE --MODEL_NAME $MODEL_NAME --OPTIMIZER $OPTIMIZER --USE_PRETRAINED_MODEL $USE_PRETRAINED_MODEL --DATA_AUGMENTATION $DATA_AUGMENTATION --DATA_NORMALIZATION $DATA_NORMALIZATION --DATA_SCALE $DATA_SCALE
done

# ##############
echo "#### RUNNING TRAINING WITH LARGE AGE ENCODER"
# ##############
USE_AGE=True
AGE_ENCODER_VERSION=large_age_encoder

for RANDOM_SEED_NUMBER in 1111 1112 1113 1114 1115
do
   python3 run_model_training_TF.py --WORKING_FOLDER $WORKING_FOLDER --IMG_DATASET_FOLDER $IMG_DATASET_FOLDER --DATASET_TYPE $DATASET_TYPE --NBR_CLASSES $NBR_CLASSES --GPU_NBR $GPU_NBR --NBR_FOLDS $NBR_FOLDS --LEARNING_RATE $LEARNING_RATE --BATCH_SIZE $BATCH_SIZE --MAX_EPOCHS $MAX_EPOCHS --USE_AGE $USE_AGE --AGE_NORMALIZATION $AGE_NORMALIZATION --AGE_ENCODER_VERSION $AGE_ENCODER_VERSION --USE_GRADCAM $USE_GRADCAM --LOSS $LOSS --RANDOM_SEED_NUMBER $RANDOM_SEED_NUMBER --MR_MODALITIES $MR_MODALITIES --DEBUG_DATASET_FRACTION $DEBUG_DATASET_FRACTION --TFR_DATA $TFR_DATA --MODEL_TYPE $MODEL_TYPE --MODEL_NAME $MODEL_NAME --OPTIMIZER $OPTIMIZER --USE_PRETRAINED_MODEL $USE_PRETRAINED_MODEL --DATA_AUGMENTATION $DATA_AUGMENTATION --DATA_NORMALIZATION $DATA_NORMALIZATION --DATA_SCALE $DATA_SCALE
done
