dataset_path: /flush3/iulta54/Data/TCGA/dataset224_t2_transversal_30_70
path_to_dataset_split: /flush/iulta54/P5-PedMRI_CBTN_v1/DEBUGGING/data_split_information.csv
root_save_path: /flush/iulta54/P5-PedMRI_CBTN_v1/DEBUGGING/trained_models
save_path: /flush/iulta54/P5-PedMRI_CBTN_v1/DEBUGGING/trained_models/TESTs_TCGA_231110/SDM4_opt_ADAM_sch_EXPONENTIAL_lr_1e-05_fold_fold_1_expdec_0.995_1133
classes_to_use:
- G2
- G4
fold_name: fold_1
model_version: SDM4
optimizer: ADAM
scheduler: EXPONENTIAL
base_lr: 1.0e-05
max_lr: 0.1
exponential_decay: 0.995
batch_size: 64
max_epochs: 100
save_histograms: false
class_weights:
- 1.5603674540682415
- 0.7357673267326733
gpu_nbr: 0
nbr_workers: 40
seed: 42
