defaults:
- _self_
- dataset: CBTN_tumor_classification_ASTR_EP_MED

working_dir: ${hydra:runtime.cwd}

dataloader_settings:
  batch_size: 128
  augmentation: True
  nbr_workers: 15
  class_stratification: True
  test_size: 0.2
  input_size: [224, 224]
  randomize_subject_labels: False
  randomize_slice_labels : False
  select_slices_in_range : null
  use_one_slice_per_subject_within_epoch: False
  img_mean: # there are just to save the standardization values
  img_std: # there are just to save the standardization values
  use_age: false
  normalize_age: true


augmentation_settings:
  rotation: 45
  brigntess_rage: 0.5
  contrast_rage: 0.5
  saturation: 0.5
  hue: 0.1

model_settings:
  use_SimCLR_pretrained_model: True
  SimCLR_prettrained_model_setitngs:
    model_path: '/flush2/iulta54/Code/P5-PediatricBrainTumorClassification_CBTN_v1/trained_model_archive/SimCLR_TESTs_20231130/SimCLR_ViT_b_16_pretrained_True_frozen_True_0_LR_1e-05_BATCH_64_TrivialAug_True_t145634'
    pretraining_dataset: cbtn
  model_version: ViT_b_16 # this can be ResNet50, ResNet18, 2DSDM4, RadResNet, ViT_b_16, ViT_b_32
  pre_trained: True
  freeze_weights: True
  percentage_freeze_weights: 0
  mlp_nodes: []
  age_encoder_mlp_nodes: []

training_settings:
  epochs: 500
  patience: 20
  learning_rate: 0.000005
  optimizer : adam # adamw, sgd, adam
  scheduler : exponential # linear_decay, cyclical, reduce_on_plateau, static
  use_look_ahead_wrapper : False
  use_class_weights: True
  random_state: 20091229
  nbr_repetitions: 2 # repetitions of cross validation
  nbr_inner_cv_folds: 5 # number of cross validations in each repetition
  run_testing: False # set to true only when model hiperparameters are tuned to get the final evaluation
  
debugging_settings:
  dataset_fraction: 1

logging_settings:
  checkpoint_path: ${hydra:runtime.cwd}/logging
  save_training_validation_test_hist: False
  start_time: None

resources:
  gpu_nbr: 0