working_folder: null
path_to_repetition_folders: '/flush2/iulta54/Code/P5-PediatricBrainTumorClassification_CBTN_v1/trained_model_archive/TESTs_20231124/ResNet50_pretrained_True_frozen_True_0.5_LR_1e-05_BATCH_32_AUGMENTATION_True_OPTIM_adam_SCHEDULER_exponential_MLPNODES_0_t100754'
save_path: null
model_settings:
  path_to_cross_validation_folder:
  model_version: null
  session_time: null
  repetition_nbr: null
dataloader_settings: 
  path_to_data_split_csv_file: null
  set_to_evaluate: 'validation' # is can be training, validation, testing
  preprocessing_settings: 
    input_size: null        
    img_mean: null
    img_std: null
resources: 
  gpu_nbr: 0
  nbr_workers: 15