defaults:
- _self_
- dataset: CBTN_tumor_classification_ASTR_EP_MED # Find a way to have two different datasets, one for the SimCLR training and one for the classification training

working_dir: ${hydra:runtime.cwd}

# these are the settings for the SimCLR dataloader, model and training
SimCLR:
  dataloader_settings:
    batch_size: 64
    nbr_workers: 15
    class_stratification: True
    test_size: 0.01
    input_size: [224, 224]
    randomize_subject_labels: False
    randomize_slice_labels : False
    select_slices_in_range : null
    use_slices_as_views: true
    img_mean: # there are just to save the standardization values
    img_std: # there are just to save the standardization values

  augmentation_settings:
    rotation: 45
    brigntess_rage: 0.5
    contrast_rage: 0.5
    saturation: 0.5
    hue: 0.1
    use_trivialAugWide: True

  model_settings:
    model_version: ResNet50 # this can be ResNet50, ResNet18, 2DSDM4, RadResNet, ViT_b_16, ViT_b_32
    pre_trained: True
    freeze_weights: True
    percentage_freeze_weights: 0

  training_settings:
    epochs: 200
    patience: 200
    learning_rate: 0.00001
    random_state: 20091229
    nbr_repetitions: 1 # repetitions of cross validation
    nbr_inner_cv_folds: 1 # number of cross validations in each repetition

debugging_settings:
  dataset_fraction: 1

logging_settings:
  checkpoint_path: ${hydra:runtime.cwd}/logging
  SimCLR_start_time: None

resources:
  gpu_nbr: 1