dataset_path: /flush3/iulta54/Data/TCGA/dataset224_t2_transversal_30_70
path_to_dataset_split: /flush/iulta54/P5-PedMRI_CBTN_v1/DEBUGGING/data_split_information.csv
root_save_path: /flush/iulta54/P5-PedMRI_CBTN_v1/DEBUGGING/trained_models
save_path: /flush/iulta54/P5-PedMRI_CBTN_v1/DEBUGGING/trained_models/TESTs_231109/ResNet9_opt_ADAM_sch_EXPONENTIAL_lr_0.0001_fold_fold_3_expdec_0.995_2118
classes_to_use:
- G2
- G4
fold_name: fold_3
model_version: ResNet9
optimizer: ADAM
scheduler: EXPONENTIAL
base_lr: 0.0001
max_lr: 0.1
exponential_decay: 0.995
batch_size: 64
max_epochs: 100
save_histograms: false
class_weights:
- 1.221951219512195
- 0.8462837837837838
gpu_nbr: 0
nbr_workers: 40
seed: 42
